Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),

]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('pizzas', views.pizzas, name = 'pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name = 'pizza'),
    path('new_comment/', views.new_comment, name ='new_comment'),
    
]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length = 100)
    
    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length = 100)

    class Meta:
        verbose_name_plural = 'toppings'
    def __str__ (self):
        return f"{self.topping_name[:50]}..."


class Reviews(models.Model):
    topping = models.ForeignKey(Topping, on_delete=models.CASCADE)
    reviews = models.TextField()
    def __str__ (self):
        return f"{self.comments[:50]}..."
        

pizzas/forms.py
from django import forms

from .models import Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['pizza_name']
        labels = {'pizza_name': ''}

pizzas/views.py
from django.shortcuts import render, redirect

from .forms import PizzaForm
from .models import Pizza, Topping

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas} #use pizza key in html file, value in views file

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    context = {'pizza':pizza, 'toppings':toppings}
    
    return render(request, 'pizzas/pizza.html', context)

def new_comment(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save()


            return redirect('pizzas:pizzas')

    context = {'form': form}
    return render(request, 'pizzas/new_comment.html', context)

    

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Home</a>
    <a href="{% url 'pizzas:pizzas' %}">Pizza Offerings</a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
<html>

<head>
    <style>
        p {
            text-align: center;
        }
    </style>
</head>

<body>



    <p style="color:rgb(216, 69, 25);font-size:40px;font-family:comic sans ms;">Margherita</p>
    <p style="color:rgb(255, 253, 109);font-size:40px;font-family:comic sans ms;">&</p>
    <p style="color:rgb(114, 236, 124);font-size:40px;font-family:comic sans ms;">Margaritas</p>
    <img src="https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80"
        alt="pizza" style="width:500px;height:500px" class="center;">
    <img src="https://images.unsplash.com/photo-1572552635104-daf938e0aa1f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
        alt="pizza" style="width:500px;height:500px" class="center;">


    {% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}


{% block content %}

<p>Add a comment</p>

<form action="{% url 'pizzas:new_comment' %}" method='post'>
    {% csrf_token %}

    {{ form.as_p }}

    <button name="post comment">Add comment</button>
</form>


{% endblock content %}

pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %}


{% block content %}

<p>Add a comment</p>

<form action="{% url 'pizzas:new_pizza' %}" method ='post'>
    {% csrf_token %}
    
    {{ form.as_p }}

    <button name="post comment">Add comment</button>
    </form>

    
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>
    Pizza: {{ pizza }}
</p>

<ul>
    <img src="https://laurenslatest.com/wp-content/uploads/2021/01/margherita-pizza-recipe-04-500x500.jpg" alt="pizza"
        style="width:250px;height:250px;">
    {% for t in toppings %}
    <li>
        <p> {{ t }}</p>

    </li>

    {% empty %}
    <li>No availabilities...</li>
    {% endfor %}
</ul>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}

<p>Current Pizza Offerings...</p>


<ul>

    {% for p in pizzas %}

    <li>
        <a href="{% url 'pizzas:pizza' p.id %}"> {{ p }}</a>

    </li>
    {% empty %}
    <li> No Pizzas Available... </li>
    {% endfor %}


</ul>

<a href="{% url 'pizzas:new_comment' %}">Add a comment</a>

{% endblock content %}